#!/bin/bash

# Local Development Setup Script
# Generated by skit-fast-cli

echo "🚀 Setting up local development environment..."

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker to run local services."
    exit 1
fi

# Check if Docker Compose is available
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose."
    exit 1
fi

# Start local services
echo "📦 Starting local services..."
npm run services:start

# Wait a moment for services to start
sleep 5

echo "✅ Local development environment is ready!"
echo ""
echo "🌐 Available services:"
echo "   • SvelteKit app: http://localhost:3000 (run 'npm run dev')"
echo "   • PocketBase: http://localhost:8090 (if selected)"
echo "   • MongoDB: localhost:27017 (if selected)"
echo "   • Redis: localhost:6379 (if selected)"
echo "   • LiteLLM: http://localhost:4000 (if selected)"
echo "   • Qdrant: http://localhost:6333 (if selected)"
echo ""
echo "📋 Next steps:"
echo "   1. Run 'npm run dev' to start the SvelteKit development server"
echo "   2. Open http://localhost:3000 in your browser"
echo "   3. Run 'npm run services:stop' when done developing"
echo ""
echo "🔍 View service logs: npm run services:logs"